ORBS.setFullScreenGameCss()
var renderer = new ORBS.renderer({renderState: update})
var scene = new ORBS.scene()
renderer.scene.add()
console.log(renderer)
console.log(scene)
renderer.setSize(window.innerWidth, window.innerHeight)
document.body.append(renderer.canvas)
